<?php
namespace Z61\Classifieds\XF\Admin\Controller;

use XF\Mvc\FormAction;

class Forum extends XFCP_Forum
{
    protected function saveTypeData(FormAction $form, \XF\Entity\Node $node, \XF\Entity\AbstractNode $data)
    {
        parent::saveTypeData($form, $node, $data); // TODO: Change the autogenerated stub

        $form->setup(function() use ($data)
        {
            $data->z61c_replace_action_btn = $this->filter('z61c_replace_action_btn', 'bool');
        });
    }
}