<?php
return array (
  'option_group.acp' => 'Admin control panel',
  'option_group.alerts' => 'User alerts and notifications',
  'option_group.appearance' => 'Appearance',
  'option_group.attachments' => 'Attachments',
  'option_group.basicBoard' => 'Basic options',
  'option_group.boardActive' => 'Board active',
  'option_group.censoringOptions' => 'Censoring',
  'option_group.debug' => 'Debug options',
  'option_group.discourager' => 'User discouragement and discipline',
  'option_group.discussionOptions' => 'Threads,  discussions and conversations',
  'option_group.emailOptions' => 'Email options',
  'option_group.fs_pgp_encryption' => 'Fs-PGPEncryption',
  'option_group.fs_register_steps' => '[FS] Register Steps',
  'option_group.imageLinkProxy' => 'Image and link proxy',
  'option_group.logging' => 'Logging options',
  'option_group.mediaEmbedding' => 'Media embedding',
  'option_group.messageOptions' => 'Messages',
  'option_group.newsfeed' => 'News feed',
  'option_group.nodeList' => 'Node & forum list',
  'option_group.performance' => 'System and performance',
  'option_group.pwa' => 'PWA options',
  'option_group.searchOptions' => 'Search options',
  'option_group.seo' => 'Search engine optimization (SEO)',
  'option_group.serviceProviders' => 'External service providers',
  'option_group.sharing' => 'Sharing',
  'option_group.sitemap' => 'XML sitemap generation',
  'option_group.spam' => 'Spam management',
  'option_group.stats' => 'Statistics and metrics',
  'option_group.tagging' => 'Content tagging',
  'option_group.tapatalkBYOOptions' => '
        Tapatalk - Build Your Own - Options',
  'option_group.tapatalkDeepLinkOptions' => '
        Tapatalk - Mobile App Deep Linking (BYO Branded App and Tapatalk)',
  'option_group.tapatalkOptions' => '
        Tapatalk',
  'option_group.tl_groups' => '[tl] Social Groups',
  'option_group.users' => 'User options',
  'option_group.usersAndRegistration' => 'User registration',
);