<?php
return array (
  'thread_prefix.1' => 'Bronx',
  'thread_prefix.10' => 'Queens',
  'thread_prefix.11' => 'Statewide',
  'thread_prefix.12' => 'Staten Island',
  'thread_prefix.13' => 'Uptown',
  'thread_prefix.14' => 'Upstate',
  'thread_prefix.15' => 'Westchester',
  'thread_prefix.16' => 'Yonkers',
  'thread_prefix.17' => 'Dallas',
  'thread_prefix.18' => 'Austin',
  'thread_prefix.19' => 'Houston',
  'thread_prefix.2' => 'Brooklyn',
  'thread_prefix.20' => 'San Antonio',
  'thread_prefix.21' => 'New Orleans',
  'thread_prefix.22' => 'Baton Rouge',
  'thread_prefix.23' => 'Santa Fe',
  'thread_prefix.24' => 'Albuquerque',
  'thread_prefix.25' => 'Denver',
  'thread_prefix.26' => 'Tulsa',
  'thread_prefix.27' => 'Oklahoma City',
  'thread_prefix.28' => 'St Louis',
  'thread_prefix.29' => 'Kansas city',
  'thread_prefix.3' => 'Buffalo',
  'thread_prefix.30' => 'Omaha',
  'thread_prefix.31' => 'Little Rock',
  'thread_prefix.4' => 'Greater NY',
  'thread_prefix.5' => 'Hudson Valley',
  'thread_prefix.6' => 'Long Island',
  'thread_prefix.7' => 'Manhattan',
  'thread_prefix.8' => 'Midtown',
  'thread_prefix.9' => 'NYC',
);