<?php
return array (
  'user_field_desc.HairLength' => 'How long is your hair?',
  'user_field_desc.HatedDiscussionTopics' => '',
  'user_field_desc.POCFriendly' => '',
  'user_field_desc.PublicPhoneNumber' => 'Public phone number. This will display on your profile. (Format: (NNN)NNN-NNNN)',
  'user_field_desc.ReceiveEmailfromOther' => 'Occasionally, administrators and/or fellow members might wish to dispatch email notifications or messages. If you prefer not to get emails from specific individuals, you can deactivate these choices here.',
  'user_field_desc.Screening' => '',
  'user_field_desc.age' => 'What is the age you would like to display? You must be over 21.',
  'user_field_desc.biography' => 'A concise portrayal of who you are. (5 minutes - maximum 250 words).',
  'user_field_desc.bodyType' => 'How would you characterize your physique?',
  'user_field_desc.city' => 'What city do you live in or near?',
  'user_field_desc.donationForTime' => '',
  'user_field_desc.emailAdrress' => 'The SWB Board employs an inline emailing system, ensuring that unless you respond, the sender remains unaware of your email address. Only input your email here if you intend for it to be visible to the public. Within your privacy settings, you\'ll be able to decide who has access to this information.',
  'user_field_desc.ethnicity' => '',
  'user_field_desc.eyes' => '',
  'user_field_desc.facebook' => '',
  'user_field_desc.gender' => '',
  'user_field_desc.haircolor' => '',
  'user_field_desc.height' => '',
  'user_field_desc.likedDiscussionTopics' => '',
  'user_field_desc.offerLessons' => '',
  'user_field_desc.piercings' => 'How many piercings do you have?',
  'user_field_desc.region' => 'West: WA, OR, CA, etc; Central: TX, IL, GA, etc; East: NJ, NY, PA, etc;',
  'user_field_desc.skype' => '',
  'user_field_desc.smoker' => 'Do you consume at least one cigarette per week?',
  'user_field_desc.specials' => '',
  'user_field_desc.state' => 'What is your place of residence?',
  'user_field_desc.tattoos' => 'How many tattoos do you have?',
  'user_field_desc.twitter' => '',
  'user_field_desc.weight' => 'Approx. how much do you weigh in lbs?',
);