<?php
return array (
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.bumpThreadPermissions' => '[OzzModz/Banxix] Bump Thread',
  'permission_interface.conversationModeratorPermissions' => 'Conversation moderator permissions',
  'permission_interface.conversationPermissions' => 'Conversation permissions',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.fs_move_Thread_perms_group' => '[FS] Move Post',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.xa_scComment' => 'Showcase: Comment permissions',
  'permission_interface.xa_scCommentModerator' => 'Showcase: Comment moderator permissions',
  'permission_interface.xa_scItem' => 'Showcase: Item permissions',
  'permission_interface.xa_scItemModerator' => 'Showcase: Item moderator permissions',
  'permission_interface.xa_scRating' => 'Showcase: Rate/Review permissions',
  'permission_interface.xa_scRatingModerator' => 'Showcase: Rate/Review moderator permissions',
  'permission_interface.xa_scSeries' => 'Showcase: Series permissions',
  'permission_interface.xa_scSeriesModerator' => 'Showcase: Series moderator permissions',
  'permission_interface.xc_profile_views' => '[XenConcept] Profile views',
  'permission_interface.xfmgAlbum' => 'XFMG: Album permissions',
  'permission_interface.xfmgAlbumModerator' => 'XFMG: Album moderator permissions',
  'permission_interface.xfmgComment' => 'XFMG: Comment permissions',
  'permission_interface.xfmgCommentModerator' => 'XFMG: Comment moderator permissions',
  'permission_interface.xfmgMedia' => 'XFMG: Media permissions',
  'permission_interface.xfmgMediaModerator' => 'XFMG: Media moderator permissions',
  'permission_interface.xfmgNote' => 'XFMG: Note permissions',
  'permission_interface.xfmgNoteModerator' => 'XFMG: Note moderator permissions',
  'permission_interface.xfmgUploadQuotas' => 'XFMG: Upload quotas',
);