<?php
return array (
  'user_field_title.HairLength' => 'Hair Length',
  'user_field_title.HatedDiscussionTopics' => 'Topics I hate discussing',
  'user_field_title.POCFriendly' => 'POC Friendly',
  'user_field_title.PublicPhoneNumber' => 'Phone Number:',
  'user_field_title.ReceiveEmailfromOther' => 'Receive Email from Other Members',
  'user_field_title.Screening' => 'Screening',
  'user_field_title.age' => 'Age',
  'user_field_title.biography' => 'Biography',
  'user_field_title.bodyType' => 'Body Type',
  'user_field_title.city' => 'City',
  'user_field_title.donationForTime' => 'Donations for Time',
  'user_field_title.emailAdrress' => 'Email Adress',
  'user_field_title.ethnicity' => 'Ethnicity',
  'user_field_title.eyes' => 'Eyes',
  'user_field_title.facebook' => 'Facebook',
  'user_field_title.gender' => 'Gender',
  'user_field_title.haircolor' => 'Hair Color',
  'user_field_title.height' => 'Height',
  'user_field_title.likedDiscussionTopics' => 'Some topics I like discussing',
  'user_field_title.offerLessons' => 'Offer Lessons',
  'user_field_title.piercings' => 'Piercings',
  'user_field_title.region' => 'Region',
  'user_field_title.skype' => 'Skype',
  'user_field_title.smoker' => 'Smoker',
  'user_field_title.specials' => 'Specials',
  'user_field_title.state' => 'State',
  'user_field_title.tattoos' => 'Tattoos',
  'user_field_title.twitter' => 'Twitter',
  'user_field_title.weight' => 'Weight',
);