<?php
return array (
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.conversationModeratorPermissions' => 'Conversation moderator permissions',
  'permission_interface.conversationPermissions' => 'Conversation permissions',
  'permission_interface.dbtechCredits' => 'DragonByte Credits permissions',
  'permission_interface.dbtechCreditsModerator' => 'DragonByte Credits moderator permissions',
  'permission_interface.dbtechEcommerce' => 'DragonByte eCommerce permissions',
  'permission_interface.dbtechEcommerceAdmin' => 'DragonByte eCommerce admin permissions',
  'permission_interface.dbtechEcommerceModerator' => 'DragonByte eCommerce moderator permissions',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.fs_Thread_Thumbnail_perms' => '[FS] Thread Thumbnail',
  'permission_interface.fs_auction_permissions' => 'FS Auction Plugin Permissions',
  'permission_interface.fs_escrow' => 'Escrow  Permissions',
  'permission_interface.fs_forum_group_permission' => 'FS Forum Group Permission',
  'permission_interface.fs_move_Thread_perms_group' => '[FS] Move Post',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.resourceModeratorPermissions' => 'Resource moderator permissions',
  'permission_interface.resourcePermissions' => 'Resource permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.xa_scComment' => 'Showcase: Comment permissions',
  'permission_interface.xa_scCommentModerator' => 'Showcase: Comment moderator permissions',
  'permission_interface.xa_scItem' => 'Showcase: Item permissions',
  'permission_interface.xa_scItemModerator' => 'Showcase: Item moderator permissions',
  'permission_interface.xa_scRating' => 'Showcase: Rate/Review permissions',
  'permission_interface.xa_scRatingModerator' => 'Showcase: Rate/Review moderator permissions',
  'permission_interface.xa_scSeries' => 'Showcase: Series permissions',
  'permission_interface.xa_scSeriesModerator' => 'Showcase: Series moderator permissions',
  'permission_interface.xc_thread_article' => '[FS] Thread Change Article',
);